---
- name: update packages
  become: yes
  become_method: sudo
  apt: upgrade=dist update_cache=yes

- name: install libraries using APT
  apt: name={{ item }} state=latest
  become: yes
  become_method: sudo
  with_items:
    - vim
    - openvpn
    - openssh-server
    - cmake
    - curl
    - xclip
    - tree
